* emacs-mine - An Emacs Study Kit
/(This was originally my emacs configuration backup repository)/

There are hundreds of emacs config repositories on github (prelude, emacs-live,
spacemacs, etc). I started by including them individualy as submodule (so called
"config suit") and load particular suit specified by environment variable
$EMACS_CONFIG on emacs startup. Thus I can easily taste and study them, not mess
up my own configuration.

** Suit management will not use submodule
- How to define suit? (name, repos location, ...)
- Maybe not use environment variable too?
- Which famous suits too include by default?
** Use cask and ecukes for study purpose?
** Functions for emacs study?
- Insert command name by key press
** Change "mine" suit to "kess - Keep Emacs Simple, Stupid" suit
- [X] make kess as default
- [X] C-` prefix key map, mainly for mark related commands
- [ ] C-backspace backward-delete-line
- [ ] M-backspace backward-delete-word
** Thoughts
*** Preview for dired-mode
** Suit Load
#+begin_src emacs-lisp
;;; emacs-mine.el --- Emacs initial file
;; Load by init.el use org-babel

;; Author: Wu Tiefeng <IcebergWTF@qq.com>
;; Maintainer: Wu Tiefeng

;;; Commentary:

;;; Code:

;; Common setting and variables
(prefer-coding-system 'utf-8)

(defvar suit-init-file "init.el")

;; Load specified config suit from the following list:
;;    live - "emacs-live" (git://github.com/overtone/emacs-live.git)
;; prelude - "prelude" (git://github.com/bbatsov/prelude.git)
;;   space - "spacemacs" (git://github.com/syl20bnr/spacemacs.git)
;;   bling - "bling's KISS dotemacs" (git://github.com/bling/dotemacs.git)
;;obsolete - "my first config suit 'mine' which is obsolete now"
;;    kess - "my 'Keep Emacs Simple, Stupid' config suit" (default)
(let* ((suits '("live" "prelude" "space" "bling" "obsolete" "kess"))
       (env (getenv "EMACS_CONFIG"))
       (suit (or (and (member env suits) env) "kess")))
  (setenv "EMACS_CONFIG" suit) ; In case environment variable not set
  (message "start config suit \"%s\" loading on %s" suit system-type)

  ;; Set common package 'elpa' directory to share packages between packages
  ;; NOTE: some suits (like prelude) might change it to their own directory
  (require 'package)
  (setq package-user-dir (concat user-emacs-directory "elpa"))

  ;; Load suit preset file if exists
  ;; Opportunity for adjusting given suit, such as change suit-init-file, etc.
  (load (concat user-emacs-directory "suits/" "suit" ".el") 'noerror)

  ;; HACK: Change user-emacs-directory to suit directory
  (setq user-emacs-directory (concat user-emacs-directory suit "/"))
  (add-to-list 'load-path user-emacs-directory)

  ;; Load config suit
  (load (concat user-emacs-directory suit-init-file))

  ;; Set emacs customize file and load, personal settings can load through
  ;; .personal.el file as well
  (setq custom-file "~/.personal.el")
  (load custom-file 'noerror)

  ;; Since this emacs configuration is used on other computers, load local
  ;; setting such as font size, frame size through .local.el file, if exists.
  (load "~/.local.el" 'noerror)

  (message "config suit \"%s\" loaded" suit))

;;; init.el ends here
#+end_src
