#+TITLE: emacs-mine - An emacs study kit
#+STARTUP: content
#+OPTIONS: toc:4 h:4

* Description
  /(This was originally my emacs configuration backup repository)/

  There are hundreds of emacs config repositories on github (prelude,
  emacs-live, spacemacs, etc). I started by including them individualy
  as submodule (so called "/emacs mine/") and load particular /mine/
  specified by environment variable $EMACS_MINE on emacs startup. Thus I
  can easily taste and study them, not mess up my own configuration.

  Since the environment variable solution is not convenient, new
  /mine/ management and selection is WIP.
* Boot your emacs
** Load mine list and selection UI
   - read all directories from ~/.emacs.d/mines as mine list
   - display a somewhat selection UI to choose particular mine to load
   - remember last used mine as default choice, if not choose by user
     after few seconds automaticly use it
     #+BEGIN_SRC emacs-lisp
      (setq mine "constnil")
      (message "start mine \"%s\" loading on %s" mine system-type)
     #+END_SRC
** Loading process
   #+BEGIN_SRC emacs-lisp
     ;; ~/.preset.el is the place to put pre configs on local machine
     (load (expand-file-name "~/.preset.el") 'noerror)

     (setq user-emacs-directory (concat user-emacs-directory "mines/" mine "/"))
     (message "set root path of \"%s\": %s" mine user-emacs-directory)

     (require 'package)
     (setq package-user-dir (concat user-emacs-directory "elpa/"))
     (message "set 'elpa' directory of \"%s\": %s" mine package-user-dir)

     ;; Load mine preset file if exists.
     ;; Opportunity for adjusting given mine, such as change mine-init-file, etc.
     (load (concat user-emacs-directory mine ".el") 'noerror)

     ;; Set emacs customize file for loading mine.
     (setq custom-file (concat user-emacs-directory ".custom.el"))
     (load custom-file 'noerror)

     (let ((init-file (concat user-emacs-directory mine ".el")))
       (if (file-exists-p init-file)
	   (setq user-init-file init-file)
	 (setq user-init-file (concat user-emacs-directory "init.el"))))
     (load user-init-file)

     ;; Personal settings can be set in ~/.personal.el file, if exists.
     (load (expand-file-name "~/.personal.el") 'noerror)

     ;; Load post set file if exists. I use it to specify machine local
     ;; settings such as font size, frame size, etc.
     (load (expand-file-name "~/.postset.el") 'noerror)

     ;; Done
     (message "mine \"%s\" loaded" mine)
   #+END_SRC
