#+TITLE: emacs-mine - An emacs study kit
#+STARTUP: content
#+OPTIONS: toc:4 h:4

* Preface
/(This was originally my emacs configuration backup repository)/

There are hundreds of emacs config repositories on github (prelude, emacs-live,
spacemacs, etc). I started by including them individualy as submodule (so called
"config suit") and load particular suit specified by environment variable
$EMACS_CONFIG on emacs startup. Thus I can easily taste and study them, not mess
up my own configuration.

* Suit management will not use submodule
- How to define suit? (name, repos location, ...)
- Maybe not use environment variable too?
- Which famous suits too include by default?
* Use cask and ecukes for study purpose?
* Functions for emacs study?
- Insert command name by key press
* Change "mine" suit to "kess - Keep Emacs Simple, Stupid" suit
- [X] make kess as default
- [X] C-` prefix key map, mainly for mark related commands
- [ ] C-backspace backward-delete-line
- [ ] M-backspace backward-delete-word
* Learning Plan
** As text editor
*** global search (grep/ack/ag)
*** open recent file
** As system management tool
*** eshell-mode
*** shell-mode
*** term-mode
*** package management
**** el-get
**** package.el
**** use-package
** As personal task management tool
*** OrgMode
** As programming IDE
*** project management
**** projectile
***** Register for known project?
- 0-9，total 10 registers
- C-u 0..9 C-c p p switch project and record to register
- C-u 0..9 followed by projectile commands to operate agaitest register recorded
  project
**** find-file-in-project
*** pair wrapping
- smartparens
- wrap-region
- autopair
*** comment management
** As elisp IDE
*** paredit
*** emacs-lisp-mode
*** lisp-interaction-mode
*** cask
*** ecukes
** As ruby IDE
** As clojure IDE
*** clojure-mode
*** cider
** As C# IDE
*** csharp-mode
*** omnisharp-emacs
** Dig into
*** [[file+emacs:~/warehouse/projects/references/emacs/][emacs source code]]
**** TODO Build Emacs under Msys2 [[https://chriszheng.science/2015/03/19/Chinese-version-of-Emacs-building-guideline/][reference]]
***** Install Msys2 packages
pacman -S base-devel mingw-w64-x86_64-toolchain \
mingw-w64-x86_64-xpm-nox mingw-w64-x86_64-libtiff \
mingw-w64-x86_64-giflib mingw-w64-x86_64-libpng \
mingw-w64-x86_64-libjpeg-turbo mingw-w64-x86_64-librsvg \
mingw-w64-x86_64-libxml2 mingw-w64-x86_64-gnutls --needed
***** Run autogen
./autogen.sh
***** Configure
PKG_CONFIG_PATH=/mingw64/lib/pkgconfig ./configure --host=x86_64-w64-mingw32 \
--target=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --prefix=/usr/bin --with-wide-int \
--with-jpeg --with-xpm --with-png --with-tiff --with-rsvg --with-xml2 \
--with-gnutls --without-imagemagick
***** Make
make && make install
***** progress
configure failure: no socklen_t
*** how emacs key binding works
- [[file:~/.emacs.d/notes/keymap.org][notes]] after reading emacs lisp manual
*** find key binding's original and current value in all minor/major modes

* Thoughts
** Preview for dired-mode
** Suit Load
#+BEGIN_SRC emacs-lisp
  ;; Common setting and variables
  (prefer-coding-system 'utf-8)
  (set-language-environment 'utf-8)
  (set-locale-environment "utf-8")

  (defvar suit-init-file "init.el")

  ;; Load specified config suit from the following list:
  ;;    live - "emacs-live" (git://github.com/overtone/emacs-live.git)
  ;; prelude - "prelude" (git://github.com/bbatsov/prelude.git)
  ;;   space - "spacemacs" (git://github.com/syl20bnr/spacemacs.git)
  ;;   bling - "bling's KISS dotemacs" (git://github.com/bling/dotemacs.git)
  ;;  sachac - "sacha chua's .emacs.d (git://github.com/sachac/.emacs.d.git)"
  ;;    kess - "my 'Keep Emacs Simple, Stupid' config suit" (default)
  (let* ((suits '("live" "prelude" "space" "bling" "sachac" "kess"))
         (env (getenv "EMACS_CONFIG"))
         (suit (or (and (member env suits) env) "kess")))
    (setenv "EMACS_CONFIG" suit) ; In case environment variable not set
    (message "start config suit \"%s\" loading on %s" suit system-type)

    ;; Set common package 'elpa' directory to share packages between suits
    ;; NOTE: some suits (like prelude) might change it to their own directory
    (require 'package)
    (setq package-user-dir (concat user-emacs-directory "elpa"))

    ;; Load suit preset file if exists
    ;; Opportunity for adjusting given suit, such as change suit-init-file, etc.
    (load (concat user-emacs-directory "suits/" suit ".el") 'noerror)

    ;; HACK: Change user-emacs-directory to suit directory
    (setq user-emacs-directory (concat user-emacs-directory suit "/"))
    (add-to-list 'load-path user-emacs-directory)

    ;; Load config suit
    (load (concat user-emacs-directory suit-init-file))

    ;; Set emacs customize file and load, personal settings can load through
    ;; .personal.el file as well
    (setq custom-file "~/.personal.el")
    (load custom-file 'noerror)

    ;; Since this emacs configuration is used on other computers, load local
    ;; setting such as font size, frame size through .local.el file, if exists.
    (load "~/.local.el" 'noerror)

    (message "config suit \"%s\" loaded" suit))
#+END_SRC
