#!/bin/sh

install_or_update ()
{
    name=$1
    dvs=$2
    dir=$3
    url=$4

    if [ -d "$dir/.$dvs" ]
    then
        cd $dir
        echo "--- update $name (`pwd`)"
        case $dvs in
            "git")
                git fetch --all -p
                git rebase
                ;;
            "hg")
                hg pull -u
                ;;
            "svn")
                svn up
                ;;
            *)
                echo "Unknown dvs tool: $dvs"
        esac
        cd
    else
        echo "--- install $name, $url => $dir"
        case $dvs in
            "git")
                git clone $url $dir
                ;;
            "hg")
                hg clone $url $dir
                ;;
            "svn")
                svn co $url $dir
                ;;
            *)
                echo "Unknown dvs tool: $dvs"
                ;;
        esac
    fi
}

install_or_update emacs-live    git  ~/.emacs.d/live     git://github.com/overtone/emacs-live.git
install_or_update prelude       git  ~/.emacs.d/prelude  git://github.com/bbatsov/prelude.git
install_or_update spacemacs     git  ~/.emacs.d/space    git://github.com/syl20bnr/spacemacs.git
install_or_update bling         git  ~/.emacs.d/bling    git://github.com/bling/dotemacs.git
install_or_update sacha-chua    git  ~/.emacs.d/sachac   git://github.com/sachac/.emacs.d.git
install_or_update steve-purcell git  ~/.emacs.d/purcell  git://github.com/purcell/emacs.d.git
